image:
  tag: main-STAGING_SHA

ingress:
  enabled: true
  host: jobbot3000.staging.example.test
  className: nginx
  tls:
    - secretName: jobbot3000-staging-tls-example
      hosts:
        - jobbot3000.staging.example.test
