apiVersion: v1
kind: Service
metadata:
  name: {{ include "jobbot3000.fullname" . }}
  labels:
{{- include "jobbot3000.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
{{- include "jobbot3000.selectorLabels" . | nindent 4 }}
