name: PR Reaper

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  close-stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: futuroptimist/pr-reaper@v1
        with:
          days-before-close: 30
          dry-run: false
