name: Web interface screenshots

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Chromium dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libatk1.0-0 \
            libatk-bridge2.0-0 \
            libdrm-dev \
            libgbm-dev \
            libgtk-3-0 \
            libnss3 \
            libxcomposite1 \
            libxdamage1 \
            libxrandr2 \
            libxkbcommon0 \
            xdg-utils
          sudo apt-get install -y libasound2t64 || sudo apt-get install -y libasound2
      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 20
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Capture web interface screenshots
        run: npm run web:screenshots
      - name: Commit updated screenshots
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update web screenshots"
          file_pattern: docs/screenshots/*.png
          commit_user_name: jobbot automation
          commit_user_email: actions@github.com
